### ISSUE TITLE
Try new `openai` package with built-in edge support?

### ISSUE THREAD

**Issue by rattrayalex** [dan-kwiat/openai-edge#11]
Hi there,

Thanks for making this package! I'm helping build openai's new v4 npm package, which includes edge support built in (along with several other niceities). Would you be willing to try it out? 

https://github.com/openai/openai-node/discussions/182

**Comment by dan-kwiat** [comment]
Thanks @rattrayalex I've signposted to this in the readme and will deprecate once v4 is stable :)

**Comment by rattrayalex** [comment]
@dan-kwiat v4 is released as stable! https://www.npmjs.com/package/openai/v/4.0.0 it has extensive edge support. You're welcome to deprecate this if/when you like.
