### ISSUE TITLE
TS can't find the types with `"moduleResolution": "nodenext",`

### ISSUE THREAD

**Issue by NickHeiner** [dan-kwiat/openai-edge#6]
My project has this TSConfig set:

```json
"moduleResolution": "nodenext",
```

When I try to load `openai-edge`, I get this error: https://github.com/microsoft/TypeScript/issues/52363.

I was able to resolve it by publishing my own fork of this repo with [these changes](https://github.com/dan-kwiat/openai-edge/compare/main...NickHeiner:openai-edge:nth/attempt-to-fix-types?expand=1). The main change is to make `dist` look like:

```
find dist
dist
dist/api.d.ts
dist/common.d.ts
dist/configuration.js
dist/index.js
dist/response-types.d.ts
dist/configuration.d.ts
dist/base.js
dist/common.js
dist/base.d.ts
dist/form-data.js
dist/api.js
dist/form-data.d.ts
dist/index.d.ts
dist/response-types.js
```

I don't think what I did is necessary the best way to fix it, but it did work for me, and thus I share it here in case it helps you or anyone else.

![image](https://github.com/dan-kwiat/openai-edge/assets/829827/3bff7c6d-0d1c-4d60-9293-0928967481ce)

**Comment by lucaschultz** [comment]
I have the same problem. Do you have any plans to resolve this issue, @dan-kwiat?

**Comment by dan-kwiat** [comment]
Do you have a project example I can test?

**Comment by NickHeiner** [comment]
This is the project I was working in when I encountered this issue: https://github.com/fixie-ai/ai-jsx
