### ISSUE TITLE
Allow query parameters (Azure OpenAI support)

### ISSUE THREAD

**Issue by benvp** [dan-kwiat/openai-edge#8]
When using OpenAI through Azure, a query parameter `api-version` is required to call any of the OpenAI endpoints. (https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference).

The `options` object of the fetch api does not support adding `params` (like e.g. fetch), as they are set directly via the URL given to `fetch`.

This can easily be done with the official `openai` package. As a drop-in replacement I think adding support would be a viable option.

**Comment by dan-kwiat** [comment]
Thanks for raising this @benvp, I'll think about how best to address it

**Comment by benvp** [comment]
For my simple use case I created a fork and added an optional third parameter `searchParams` (an `URLSearchParams`) object to e.g. `createChatCompletion`, which will be appended to the `localVarPath`. 

Idk how much you are willing to change the function signatures, though.

Let me know if I can help somehow.

**Comment by ovived** [comment]
any updates? Thanks! Would love to use this with azure32k

**Comment by dan-kwiat** [comment]
Sorry for the delay @benvp - I've now added a `defaultQueryParams` option to the config:

```typescript
const config = new Configuration({
  apiKey: "your-key",
  basePath: "https://...",
  defaultQueryParams: new URLSearchParams({
    "api-version": "2023-05-15",
  }),
})
```

FYI v4 of the official `openai` should support this soon.

**Comment by benvp** [comment]
This is great! Thank you so much.

**Comment by rdvo** [comment]
Do you have an example of the new chatCompletion string how do you call the model deploymenbt on azure?

**Comment by onionhammer** [comment]
@dan-kwiat have you tested this? Can  you add a sample? I'm adding something like this and  only seeing errors.. Another difference between openai and azure openai is that the apikey is not in the bearer, but in a header called `api-key`.

```ts
const endpoint = `https://${AZURE_OPENAI_API_INSTANCE_NAME}.openai.azure.com`

new Configuration({
    // apiKey: OPENAI_KEY,
    apiKey: AZURE_OPENAI_API_KEY,
    basePath: `${endpoint}/openai/deployments/${AZURE_OPENAI_API_DEPLOYMENT_NAME}`,
    defaultQueryParams: new URLSearchParams({

        "api-version": AZURE_OPENAI_API_VERSION
    }), 
})
```

UPDATE: Okay, got it working with this code. Was a bit confusing since `baseOptions` is just an `any`

```ts
const endpoint = `https://${AZURE_OPENAI_API_INSTANCE_NAME}.openai.azure.com`

export const config = new Configuration({
    // apiKey: AZURE_OPENAI_API_KEY, // OPENAI_KEY,
    basePath: `${endpoint}/openai/deployments/${AZURE_OPENAI_API_DEPLOYMENT_NAME}`,
    defaultQueryParams: new URLSearchParams({
        "api-version": AZURE_OPENAI_API_VERSION
    }),
    baseOptions: {
        headers: {
            "api-key": AZURE_OPENAI_API_KEY,
        }
    }
})
```

Azure OpenAI also doesnt appear to support function_calls unless you use api version `2023-07-01-preview` or later, and create a deployment with the newer version of gpt-4
