### ISSUE TITLE
Is it possible to configure base url of Openai API like the official openai lib?

### ISSUE THREAD

**Issue by yunwuu** [dan-kwiat/openai-edge#9]
In some areas like the mainland of China, Openai API cannot be called directly. It would be necessary to call Openai API through a proxy. To do that, a proxy url should be set to substitute `api.openai.com`. For the official lib, I can directly set `openai.api_base` to the proxy url. Is it possible to do so in this lib? If so, how to do that? Thx.

**Comment by dan-kwiat** [comment]
@yunwuu yes, you can do that in the same way as with the official library:

```typescript
import { Configuration, OpenAIApi } from "openai-edge"
const configuration = new Configuration({
  apiKey: "YOUR_API_KEY",
  basePath: "https://example.com/api",
})
const openai = new OpenAIApi(configuration)
```

**Comment by lucasjinreal** [comment]
@dan-kwiat Hello, does this fastapi like url can work? I using basePath but it doesn't work


![image](https://github.com/dan-kwiat/openai-edge/assets/21303438/8cc7fb0f-f2f4-4f31-9c09-a21fa8d3772e)
